// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obligatorio.Infraestructura.EF;

#nullable disable

namespace Obligatorio.Infraestructura.Migrations
{
    [DbContext(typeof(ObligatorioContext))]
    [Migration("20260924023452_Historias")]
    partial class Historias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaHistoria", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("int");

                    b.Property<int>("HistoriaId")
                        .HasColumnType("int");

                    b.HasKey("CategoriasId", "HistoriaId");

                    b.HasIndex("HistoriaId");

                    b.ToTable("CategoriaHistoria");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Capitulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCapitulo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaId");

                    b.ToTable("Capitulos");

                    b.HasDiscriminator<string>("TipoCapitulo").HasValue("Capitulo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapituloInicialId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapituloInicialId");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Opcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapituloDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("CapituloId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapituloDestinoId");

                    b.HasIndex("CapituloId");

                    b.ToTable("Opcion");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.CapituloFinal", b =>
                {
                    b.HasBaseType("Obligatorio.LogicaNegocio.Entidades.Capitulo");

                    b.Property<int>("Contador")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Final");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.CapituloIntermedio", b =>
                {
                    b.HasBaseType("Obligatorio.LogicaNegocio.Entidades.Capitulo");

                    b.HasDiscriminator().HasValue("Intermedio");
                });

            modelBuilder.Entity("CategoriaHistoria", b =>
                {
                    b.HasOne("Obligatorio.LogicaNegocio.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio.LogicaNegocio.Entidades.Historia", null)
                        .WithMany()
                        .HasForeignKey("HistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Capitulo", b =>
                {
                    b.HasOne("Obligatorio.LogicaNegocio.Entidades.Historia", null)
                        .WithMany("Capitulos")
                        .HasForeignKey("HistoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Historia", b =>
                {
                    b.HasOne("Obligatorio.LogicaNegocio.Entidades.Capitulo", "CapituloInicial")
                        .WithMany()
                        .HasForeignKey("CapituloInicialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapituloInicial");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Opcion", b =>
                {
                    b.HasOne("Obligatorio.LogicaNegocio.Entidades.Capitulo", "Destino")
                        .WithMany()
                        .HasForeignKey("CapituloDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Obligatorio.LogicaNegocio.Entidades.CapituloIntermedio", null)
                        .WithMany("Opciones")
                        .HasForeignKey("CapituloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.OwnsOne("Obligatorio.LogicaNegocio.Vo.VoContrasenia", "Contrasenia", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Obligatorio.LogicaNegocio.Vo.VoEmail", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Obligatorio.LogicaNegocio.Vo.VoRol", "Rol", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Contrasenia")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Rol")
                        .IsRequired();
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.Historia", b =>
                {
                    b.Navigation("Capitulos");
                });

            modelBuilder.Entity("Obligatorio.LogicaNegocio.Entidades.CapituloIntermedio", b =>
                {
                    b.Navigation("Opciones");
                });
#pragma warning restore 612, 618
        }
    }
}
